@startuml = Desain_UML_Jurusan
skinparam ClassAttributeIconSize 0

package com.pbo {

    class Jurusan {
        - nama: String
        - kode: String
        --
        + Jurusan(nama: String, kode: String)
        + getNama(): String
        + setNama(nama: String): void
        + getKode(): String
        + setKode(kode: String): void
        + displayInfo(): void
    }

    class Mahasiswa {
        - nama: String
        - nim: String
        - usia: int
        - jurusan: Jurusan
        --
        + Mahasiswa(nama: String, nim: String, usia: int, jurusan: Jurusan)
        + getNama(): String
        + setNama(nama: String): void
        + getNim(): String
        + setNim(nim: String): void
        + getUsia(): int
        + setUsia(usia: int): void
        + getJurusan(): Jurusan
        + setJurusan(jurusan: Jurusan): void
        + displayInfo(): void
    }

        class Main {
        + main(args: String[]): void
    }

    Main -> Mahasiswa: creates
    Main -> Jurusan: creates
    Mahasiswa --> Jurusan: has-a

}

@enduml
